#!/usr/bin/env bash

#=======================================================================================================
# Author: Johandry Amador <johandry@gmail.com>
# Title:  Cloud Scripts Deployment
#
# Usage: {script_name} <option>
#
# Options:
#     -h, --help          Display this help message. bash {script_name} -h
#     -m '<description>'  Modification short description to be used in the commit
#
# Description: Script to promote changes to production
#
# Report Issues or create Pull Requests in http://github.com/johandry/CS
#=======================================================================================================

VERSION='1.0.0'
TITLE='Cloud Scripts Deployment'
GITHUB_PROJECT="CS"

source ~/bin/common.sh

DEBUG=1

# If not set, the WORKSPACE Directory is the current directory
WORKSPACE_DIR=.

git_push () {
  branch=$1
  description=$2

  info "Starting to push ${branch} branch"
  git add -u && \
  git commit -m "${description}" && \
  git push origin ${branch} && \
  ok "Brach ${branch} sucessfully deployed\n" 

  [[ $? -ne 0 ]] && warn "Deployment of brach ${branch} not required or failed"
}

deploy () {
  description=$1

  # Make sure the gh-pages branch exists
  if [[ ! -d "${SCRIPT_DIR}/../Pages" ]]
    then
    # Go to your Workspace directory
    cd "${SCRIPT_DIR}/.."
    git clone -b gh-pages git@github.com:johandry/${GITHUB_PROJECT}.git Pages
  fi

  [[ ! -d "${SCRIPT_DIR}/../${GITHUB_PROJECT}" ]] && error "Incorrect master directory name"

  cd "${SCRIPT_DIR}/.."
  if ! ef "${GITHUB_PROJECT}/install" "Pages/install" || ! ef "${GITHUB_PROJECT}/setup" "Pages/setup"
    then
    cp ${GITHUB_PROJECT}/install Pages/install
    cp ${GITHUB_PROJECT}/setup Pages/setup
    cd Pages
    git_push 'gh-pages' "${description}"
  fi

  cd "${SCRIPT_DIR}"
  git_push 'master' "${description}"
}

[[ "$#" == "0" ]] && usage && exit 0

[[ "$1" == "-m" ]] && description="$2"

[[ -z "${description}" ]] && error "The deployment need a description of the change"

deploy "${description}"
